/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCasesIndexRouteImport } from './routes/_layout/cases.index'
import { Route as LayoutCasesNewRouteImport } from './routes/_layout/cases.new'
import { Route as LayoutCasesCaseIdScenesRouteImport } from './routes/_layout/cases.$caseId.scenes'
import { Route as LayoutCasesCaseIdGenerateRouteImport } from './routes/_layout/cases.$caseId.generate'
import { Route as LayoutCasesCaseIdEvidenceRouteImport } from './routes/_layout/cases.$caseId.evidence'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasesIndexRoute = LayoutCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasesNewRoute = LayoutCasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasesCaseIdScenesRoute = LayoutCasesCaseIdScenesRouteImport.update({
  id: '/cases/$caseId/scenes',
  path: '/cases/$caseId/scenes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCasesCaseIdGenerateRoute =
  LayoutCasesCaseIdGenerateRouteImport.update({
    id: '/cases/$caseId/generate',
    path: '/cases/$caseId/generate',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCasesCaseIdEvidenceRoute =
  LayoutCasesCaseIdEvidenceRouteImport.update({
    id: '/cases/$caseId/evidence',
    path: '/cases/$caseId/evidence',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/cases/new': typeof LayoutCasesNewRoute
  '/cases/': typeof LayoutCasesIndexRoute
  '/cases/$caseId/evidence': typeof LayoutCasesCaseIdEvidenceRoute
  '/cases/$caseId/generate': typeof LayoutCasesCaseIdGenerateRoute
  '/cases/$caseId/scenes': typeof LayoutCasesCaseIdScenesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/cases/new': typeof LayoutCasesNewRoute
  '/cases': typeof LayoutCasesIndexRoute
  '/cases/$caseId/evidence': typeof LayoutCasesCaseIdEvidenceRoute
  '/cases/$caseId/generate': typeof LayoutCasesCaseIdGenerateRoute
  '/cases/$caseId/scenes': typeof LayoutCasesCaseIdScenesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/cases/new': typeof LayoutCasesNewRoute
  '/_layout/cases/': typeof LayoutCasesIndexRoute
  '/_layout/cases/$caseId/evidence': typeof LayoutCasesCaseIdEvidenceRoute
  '/_layout/cases/$caseId/generate': typeof LayoutCasesCaseIdGenerateRoute
  '/_layout/cases/$caseId/scenes': typeof LayoutCasesCaseIdScenesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/cases/new'
    | '/cases/'
    | '/cases/$caseId/evidence'
    | '/cases/$caseId/generate'
    | '/cases/$caseId/scenes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/cases/new'
    | '/cases'
    | '/cases/$caseId/evidence'
    | '/cases/$caseId/generate'
    | '/cases/$caseId/scenes'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/cases/new'
    | '/_layout/cases/'
    | '/_layout/cases/$caseId/evidence'
    | '/_layout/cases/$caseId/generate'
    | '/_layout/cases/$caseId/scenes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cases/': {
      id: '/_layout/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof LayoutCasesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cases/new': {
      id: '/_layout/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof LayoutCasesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cases/$caseId/scenes': {
      id: '/_layout/cases/$caseId/scenes'
      path: '/cases/$caseId/scenes'
      fullPath: '/cases/$caseId/scenes'
      preLoaderRoute: typeof LayoutCasesCaseIdScenesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cases/$caseId/generate': {
      id: '/_layout/cases/$caseId/generate'
      path: '/cases/$caseId/generate'
      fullPath: '/cases/$caseId/generate'
      preLoaderRoute: typeof LayoutCasesCaseIdGenerateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cases/$caseId/evidence': {
      id: '/_layout/cases/$caseId/evidence'
      path: '/cases/$caseId/evidence'
      fullPath: '/cases/$caseId/evidence'
      preLoaderRoute: typeof LayoutCasesCaseIdEvidenceRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCasesNewRoute: typeof LayoutCasesNewRoute
  LayoutCasesIndexRoute: typeof LayoutCasesIndexRoute
  LayoutCasesCaseIdEvidenceRoute: typeof LayoutCasesCaseIdEvidenceRoute
  LayoutCasesCaseIdGenerateRoute: typeof LayoutCasesCaseIdGenerateRoute
  LayoutCasesCaseIdScenesRoute: typeof LayoutCasesCaseIdScenesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCasesNewRoute: LayoutCasesNewRoute,
  LayoutCasesIndexRoute: LayoutCasesIndexRoute,
  LayoutCasesCaseIdEvidenceRoute: LayoutCasesCaseIdEvidenceRoute,
  LayoutCasesCaseIdGenerateRoute: LayoutCasesCaseIdGenerateRoute,
  LayoutCasesCaseIdScenesRoute: LayoutCasesCaseIdScenesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
